name: Deploy to Render

on:
  push:
    branches:
      - main  # or 'master' if that’s your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy
        run: curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
